<?php $catCount = 0;?>
<?php $catCountMax = 9;?>
<div class="rightBanner"></div>
<div class="catalog">
<?php foreach ($this->getStoreCategories() as $_category): ?>
<?php if ($catCount == $catCountMax) break;?>
<?php $catCount++;
      $cur_category=Mage::getModel('catalog/category')->load($_category->getId());
      $layer = Mage::getSingleton('catalog/layer');
      $layer->setCurrentCategory($cur_category);
?>
        <a href="<?php echo $this->getCategoryUrl($_category)?>" class="item">
            <div class="img"><img src="<?php echo $cur_category->getResizedImage();?>" width="150" height="130" /></div>
            <span class="name"><?php echo $_category->getName();?></span>
        </a>
<?php endforeach; ?>
</div>