<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<div id="item">
    <?php echo $this->getChildHtml('media') ?>
    <p>
       <br /><span>Код товару:<br/><b><?if (!$_product->getProductCode()){ echo $_product->getProductPlCode();} else {echo $_product->getProductCode();}?></b></span>
    </p>
    <div class="description">
        <h3>Пара слів про товар:</h3>
        <p><?=nl2br($_product->getDescription()); ?></p>
   </div>    
</div>
