<?php if($crumbs && is_array($crumbs)): ?>
<?$i=0;?>
    <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
        <?$i++;?>
        <?php if($_crumbInfo['link']): ?>
            <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
        <?php elseif($_crumbInfo['last']): ?>
            <h1><?php echo $this->htmlEscape($_crumbInfo['label']) ?></h1>
        <?php else: ?>
            <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
        <?php endif; ?>
        <?php if(!$_crumbInfo['last'] && $i!=count($crumbs)-1): ?>
            <span>/ </span>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
