<div id="footer">
    <div class="line"></div>
    <img class="cherry" src="img/cherry.gif" width="94" height="60" />
    <span class="bottomMenu">
        <a href="#"><?=$this->__('Main Page');?></a> |
        <a href="#"><?=$this->__('About Us');?></a> |
        <a href="#"><?=$this->__('Catalogue');?></a> |
        <a href="#"><?=$this->__('Contacts');?></a><br/>
        Copyright &copy; Crystal-Gallery
    </span>
    <span class="location">
        <b><?=$this->__('Address');?></b><br/>
        067-314-61-02, 067-255-23-23 <?=$this->__('Manager');?>
    </span>
</div>
