<div id="header">
    <img class="logo" src="<?=$this->getSkinUrl('images/logo.gif');?>" width="261" height="111"/>
    <img class="slogan" src="<?=$this->getSkinUrl('images/slogan.gif');?>" width="270" height="25"/>
    <div class="line"></div>
    <img class="bowl" src="<?=$this->getSkinUrl('images/bowl.gif');?>" width="204" height="235"/>
    <div class="menu">
        <?php echo $this->getChildHtml('topLinks') ?>
        <?php echo $this->getChildHtml('store_language') ?>
    </div>
</div>
