<div id="header">
    <img class="logo" src="<?=$this->getSkinUrl('images/logo.gif');?>" width="271" height="111"/>
    <div class="slogan"><?=$this->__('Slogan');?></div>
    <div class="line"></div>
    <img class="bowl" src="<?=$this->getSkinUrl('images/bowl.gif');?>" width="204" height="235"/>
    <div class="menu">
        <?php echo $this->getChildHtml('topLinks') ?>
        <?php echo $this->getChildHtml('store_language') ?>
    </div>
</div>
