<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>

<?php if(count($_links)>0): ?>

    <?php foreach($_links as $_link): ?>
        <a href="<?=$this->getBaseUrl().$_link->getUrl();?>" title="<?=$_link->getTitle();?>" <?=$_link->getAParams();?> <?if($this->getBaseUrl().$_link->getUrl() == $this->getCurrentUrl()):?>class="active"<?endif;?>>
            <?php echo $_link->getLabel() ?>
        </a>
    <?php endforeach; ?>

<?php endif; ?>
