<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
    <div id="page">
        <?php echo $this->getChildHtml('header') ?>
        <div id="content">
            <div id="menu">
                <?php echo $this->getChildHtml('left') ?>
                <a href="#" class="main">Келихи, бокали</a>
                <a href="#">Келихи для вина</a>
                <a href="#">Келихи для шампанського</a>
                <a href="#">Бокали для коньяку</a>
                <a href="#">Келихи для мартіні</a>
                <a href="#">Келихи для лікеру</a>
                <a href="#">Кухлі для пива</a>
                <a href="#">Весільні  бокали</a>
                <a href="#" class="main">Склянки</a>
                <a href="#" class="main">Чарки</a>
                <a href="#" class="main">Вази для квітів</a>
                <a href="#" class="main">Графіни, глечики, штофи</a>
                <a href="#" class="main">Підсвічники та лампи</a>
                <a href="#" class="main">Попільнички</a>
                <a href="#" class="main">Серветниці</a>
                <a href="#" class="main">Посуд для столу</a>
                <a href="#">Салатники, вази для фруктів</a>
                <a href="#">Блюда, тортівниці та підноси</a>
                <a href="#">Маслянички</a>
                <a href="#">Оселедниці</a>
                <a href="#">Чашки/блюдця</a>
                <a href="#">Цукернички</a>
                <a href="#" class="main">Сувеніри</a>
                <a href="#">Скриньки, шкатулки</a>
                <a href="#">Відерця для льоду</a>
                <a href="#">Релігійне</a>
                <a href="#">Рамки для фото</a>
                <a href="#">Статуетки</a>
                <a href="#">Мініатюри</a>
                <a href="#">Дзвіночки</a>
                <a href="#" class="main">Інші  товари та подарунки</a>
            </div>
            <div class="breadcrumb">каталог/category</div>
            <div class="catalog">
                <?php echo $this->getChildHtml('content') ?>
    <!--            <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>
    -->
            </div>
        </div>
        <div id="footer">
            <div class="line"></div>
            <img class="cherry" src="img/cherry.gif" width="94" height="60" />
            <span class="bottomMenu">
                <a href="#">головна</a> |
                <a href="#">про компанію</a> |
                <a href="#">каталог</a> |
                <a href="#">контакти</a><br/>
                Copyright &copy; Crystal
            </span>
            <span class="location">
                <b>м. Львів, вул. Б. Хмельницького 106</b><br/>
                (0322) 52-11-24, 067-255-23-23 менеджер з продажу
            </span>
        </div>
    </div>
</body>
</html>

















