<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
    <div id="page">
        <?php echo $this->getChildHtml('header') ?>
        <div id="content">
            <div id="menu">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div class="breadcrumb"><?php echo $this->getChildHtml('breadcrumbs') ?></div>
            <div class="catalog">
                <?php echo $this->getChildHtml('content') ?>
    <!--            <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>

                <a href="#" class="item">
                    <div class="img"><img src="img/items/test.jpg" width="150" height="130" /></div>
                    <span class="name">Long item name</span>
                    <span class="code">code</span>
                </a>
    -->
            </div>
        </div>
        <div id="footer">
            <div class="line"></div>
            <img class="cherry" src="img/cherry.gif" width="94" height="60" />
            <span class="bottomMenu">
                <a href="#">головна</a> |
                <a href="#">про компанію</a> |
                <a href="#">каталог</a> |
                <a href="#">контакти</a><br/>
                Copyright &copy; Art-Posud
            </span>
            <span class="location">
                <b>м. Львів, вул. Б. Хмельницького 106</b><br/>
                067-314-61-02, 067-255-23-23 менеджер з продажу
            </span>
        </div>
    </div>
</body>
</html>

















