<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body>
    <div id="page">
        <?php echo $this->getChildHtml('header') ?>
        <div id="content">
            <div id="menu">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div class="breadcrumb"><?php echo $this->getChildHtml('breadcrumbs') ?></div>
            
            <?php echo $this->getChildHtml('content') ?>
            
        </div>
        <?php echo $this->getChildHtml('footer') ?>
    </div>
</body>
</html>

















